name: Compile LaTeX
on: [push]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Set up Git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2
      - uses: tawalaya/latex-diff-action@v1
        with:
          root_file: lease.tex
        if: github.event_name != 'pull_request'
      - uses: tawalaya/latex-diff-action@v1
        with:
          root_file: bylaws.tex
          compile_diff: true
        if: github.event_name == 'pull_request'
      - uses: actions/upload-artifact@v2
        with:
          name: PDF
          path: |
            bylaws.pdf
            diff.pdf
