name: Compile LaTeX
on: [push]
jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: xu-cheng/texlive-action/full@v1
        with:
          run: |
            apk add make git
            make
      - uses: actions/upload-artifact@v2
        with:
          name: pdf
          path: bylaws.pdf
